require('config.options')
require('config.keymaps')
require('config.autocommands')
require('config.colorscheme')
require('config.packer')
require('config.plugins')
require('config.lsp')
require('config.treesitter')
