require("config.plugins.manager")

require("config.plugins.telescope")
require("config.plugins.gitSigns")
require("config.plugins.luaLine")
require("config.plugins.snippet")
require("config.plugins.treeSitter")
require("config.plugins.rainbow")
require("config.plugins.vimWiki")
require("config.plugins.venn")
